version: '3'
services:
  webapp:
    build: ./webapp
    ports:
      - '3000:5000'
    environment:
      - 'NODE_ENV=production'
    volumes:
      - ./webapp/:/src

  todos_service:
    build: ./todos_server
    ports:
      - '5003:5000'
    depends_on:
      - todos_db
    environment:
      - 'MONGO_DB_URI=mongodb://todos_db/todos'

  todos_db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'data-volume:/data/todos_db'

  calendar_service:
    build: ./calendar_server
    ports:
      - '5001:5000'
    depends_on:
      - calendar_db
    environment:
      - 'MONGO_DB_URI=mongodb://calendar_db/calendar'

  calendar_db:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - 'data-volume:/data/calendar_db'

  searcher_service:
    build: ./search_server
    ports:
      - 5002:5000

  nginx:
    image: 'nginx:latest'
    ports:
      - '5000:5000'
    volumes:
      - './webapp/client/build:/srv/www/static'
      - './default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - webapp
      - calendar_service
      - todos_service
      - searcher_service
volumes:
  data-volume:
