version: '3'
services:
  webapp:
    build: './webapp'
    ports:
      - "3000:3000"

  searcher:
    build: './searcher'
    ports:
      - "3000:3000"
    depends_on:
      - todos
      - calendar

  todos:
    build: './todos_server'
    ports:
      - "5000:5000"
    depends_on:
      - todos_db
    environment:
      - MONGO_DB_URI=mongodb://todos_db/todos

  todos_db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/todos_db

  calendar:
    build: './calendar_server'
    ports:
      - "5001:5000"
    depends_on:
      - calendar_db
    environment:
      - MONGO_DB_URI=mongodb://calendar_db/calendar

  calendar_db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/calendar_db

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webapp
      - calendar
      # - todos
volumes:
  data-volume: