version: '3'
services:
  webapp:
    build: ./webapp
    ports:
      - '3000:3000'

  todos_service:
    build: ./todos_server
    ports:
      - '5000:5000'
    depends_on:
      - todos_db
    environment:
      - 'MONGO_DB_URI=mongodb://todos_db/todos'

  todos_db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'data-volume:/data/todos_db'

  calendar_service:
    build: ./calendar_server
    ports:
      - '5001:5000'
    depends_on:
      - calendar_db
    environment:
      - 'MONGO_DB_URI=mongodb://calendar_db/calendar'

  calendar_db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'data-volume:/data/calendar_db'

  searcher_service:
    build: ./searcher_service
    ports:
      - 5002:5000

  nginx:
    image: 'nginx:latest'
    ports:
      - '8080:8080'
    volumes:
      - './web/public:/srv/www/static'
      - './default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - webapp
      - calendar
volumes:
  data-volume: null